### ISSUE TITLE
macos markdown preview code block issues

### ISSUE THREAD

**Issue by blissend** [sn-extensions/advanced-markdown-editor#40]
The editor called Markdown Pro in preview mode has a display issue with code blocks. For really long lines it doesn't extend the visual block all the way horizontally as shown here... https://imgur.com/a/AvW7KN5.

The same editor on the last line in preview mode, inline code blocks cuts off letters like `g` and `y` of the line above as shown here... https://imgur.com/a/QKABIAK

Let me know if you need any more information.

**Comment by joshcsullivan** [comment]
Related: https://github.com/standardnotes/forum/issues/1008#issue-635614874

When running SN from PS and opening a note in the Markdown Pro editor, I see this:

```
PackageManager: Extracting C:\Users\USERNAME~1\AppData\Local\Temp\Standard Notes\downloads\Markdown Pro.zip to C:\Users\USERNAME\AppData\Roaming\Standard Notes\Extensions\org.standardnotes.advanced-markdown-editor
(node:9832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:9832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
PackageManager: Installed component Markdown Pro
PackageManager: received sync event for: Markdown Pro (1.3.7) (deleted: false)
PackageManager: received sync event for: Markdown Pro (1.3.7) (deleted: false)
Uncaught exception SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\USERNAME\AppData\Local\Programs\standard-notes\resources\app.asar\dist\index.js:22:255307)
    at IncomingMessage.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

OS: Windows 1909 Enterprise
SN: 3.4.2-beta1
Markdown Pro: 1.3.7

**Comment by ningsongshen** [comment]
@joshcsullivan the code block issue should be fixed now. Thanks for using Standard Notes!
